import Vue from 'vue'
import {Button
        ,ButtonGroup
        ,Row
        ,Col
        ,Input
        ,Form
        ,FormItem
        ,Message
        ,Container
        ,Carousel
        ,CarouselItem
        ,Dialog
        ,Upload
        ,Dropdown
        ,DropdownMenu
        ,DropdownItem
        ,Divider
        ,Header
        ,Main
        ,Card
        ,Avatar
        ,Aside
        ,Badge
        ,Image
        ,Menu
        ,MenuItem
        ,Submenu
        ,MenuItemGroup
        ,Radio
        ,Select
        ,Option
        ,RadioGroup
        ,RadioButton
        ,Tabs 
        ,Steps
        ,Step
        ,TabPane
        ,Tag
        ,InputNumber
        ,Table
        ,TableColumn
        ,Popover} from 'element-ui'
Vue.use(Popover)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(InputNumber)
Vue.use(Tag)
Vue.use(Divider)
Vue.use(Steps)
Vue.use(Step)
Vue.use(ButtonGroup)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Button)
Vue.use(Row)
Vue.use(Col)
Vue.use(Input)
Vue.use(Form)
Vue.use(Container)
Vue.use(Dialog)
Vue.use(Upload)
Vue.use(Header)
Vue.use(Main)
Vue.use(Select)
Vue.use(Option)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Avatar)
Vue.use(Card)
Vue.use(Aside)
Vue.use(Badge)
Vue.use(Image)
Vue.use(FormItem)
Vue.use(Radio)
Vue.use(RadioButton)
Vue.use(RadioGroup)
Vue.prototype.$message = Message

